kind: Namespace
apiVersion: v1
metadata:
  name: sampleapp
spec: {}
status: {}

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: tiller
  namespace: sampleapp

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-manager
  namespace: sampleapp
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-binding
  namespace: sampleapp
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: sampleapp
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io